package main

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// sha256sum 的输出格式是 "<hex>  <文件名>"，但发布时文件名可能与我们请求的名字
// 不同（重命名过、或 CI 改了产物名）。所以只取行首哈希，不依赖文件名。
func TestParseSha256(t *testing.T) {
	good := "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  dsh-admin-linux-amd64\n"
	got, err := parseSha256(good)
	if err != nil || got != "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" {
		t.Fatalf("解析失败：got=%q err=%v", got, err)
	}

	// 大写应被归一成小写（不同工具的 sha256 输出大小写不一致）
	up := "E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855  x\n"
	if got, err := parseSha256(up); err != nil || got != strings.ToLower(got) {
		t.Fatalf("大写哈希未归一：got=%q err=%v", got, err)
	}

	// 前后有空行 / 无关行时应跳过
	mixed := "\n# generated by CI\n" + good + "\n"
	if got, err := parseSha256(mixed); err != nil || len(got) != 64 {
		t.Fatalf("含噪声行时解析失败：got=%q err=%v", got, err)
	}

	// 非法输入必须报错，不能返回空串让调用方拿空哈希去比对
	bad := []string{
		"",
		"\n\n",
		"not a hash",
		"abc123",
		"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b85", // 63 位
		"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
	}
	for _, b := range bad {
		if got, err := parseSha256(b); err == nil {
			t.Errorf("非法输入 %q 应报错，实际返回 %q", b, got)
		}
	}
}

// installBinary 是自更新里唯一改文件系统的一段。重点验证：
//   - 成功后 target 是新内容、权限可执行、旧内容留在 .bak
//   - target 不存在时也能装（备份置空）
//   - 失败路径不破坏 target
func TestInstallBinary(t *testing.T) {
	dir := t.TempDir()
	target := filepath.Join(dir, "dsh-admin")
	if err := os.WriteFile(target, []byte("OLD"), 0o755); err != nil {
		t.Fatal(err)
	}

	backup, err := installBinary(target, []byte("NEW-CONTENT"))
	if err != nil {
		t.Fatalf("installBinary 失败：%v", err)
	}
	got, _ := os.ReadFile(target)
	if string(got) != "NEW-CONTENT" {
		t.Errorf("target 内容 = %q，期望 NEW-CONTENT", got)
	}
	if backup == "" {
		t.Error("应返回备份路径")
	} else if b, _ := os.ReadFile(backup); string(b) != "OLD" {
		t.Errorf("备份内容 = %q，期望 OLD", b)
	}
	// 必须可执行，否则重启后起不来
	if st, err := os.Stat(target); err != nil {
		t.Fatal(err)
	} else if st.Mode().Perm()&0o111 == 0 {
		t.Errorf("target 权限 = %v，缺少可执行位", st.Mode().Perm())
	}
	// 临时文件不应残留
	left, _ := filepath.Glob(filepath.Join(dir, ".dsh-admin.new.*"))
	if len(left) != 0 {
		t.Errorf("残留临时文件：%v", left)
	}
}

// target 不存在时也要能装（首次安装 / .bak 场景）
func TestInstallBinaryNoExistingTarget(t *testing.T) {
	dir := t.TempDir()
	target := filepath.Join(dir, "dsh-admin")

	backup, err := installBinary(target, []byte("FRESH"))
	if err != nil {
		t.Fatalf("target 不存在时应能安装：%v", err)
	}
	if backup != "" {
		t.Errorf("target 不存在时不应有备份，实际 %q", backup)
	}
	if got, _ := os.ReadFile(target); string(got) != "FRESH" {
		t.Errorf("内容 = %q，期望 FRESH", got)
	}
}

// 目录不可写时必须报错，且不能留下半截文件
func TestInstallBinaryUnwritableDir(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("root 会无视权限位，跳过")
	}
	dir := t.TempDir()
	target := filepath.Join(dir, "dsh-admin")
	if err := os.WriteFile(target, []byte("OLD"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(dir, 0o500); err != nil {
		t.Fatal(err)
	}
	defer os.Chmod(dir, 0o700) // 让 TempDir 清理能进行

	if _, err := installBinary(target, []byte("NEW")); err == nil {
		t.Error("目录不可写时应报错")
	}
	os.Chmod(dir, 0o700)
	if got, _ := os.ReadFile(target); string(got) != "OLD" {
		t.Errorf("失败后 target 被破坏：%q", got)
	}
}

// 只支持有发布产物的架构；其他架构必须明确报错，而不是去下一个不存在的文件
func TestPanelArch(t *testing.T) {
	arch, err := panelArch()
	switch runtime.GOARCH {
	case "amd64", "arm64":
		if err != nil || arch != runtime.GOARCH {
			t.Errorf("GOARCH=%s 应返回对应产物名，实际 arch=%q err=%v", runtime.GOARCH, arch, err)
		}
	default:
		if err == nil {
			t.Errorf("GOARCH=%s 应报错，实际返回 %q", runtime.GOARCH, arch)
		}
	}
}
