package main

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// sha256sum 的输出格式是 "<hex>  <文件名>"，但发布时文件名可能与我们请求的名字
// 不同（重命名过、或 CI 改了产物名）。所以只取行首哈希，不依赖文件名。
func TestParseSha256(t *testing.T) {
	good := "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  dsh-admin-linux-amd64\n"
	got, err := parseSha256(good)
	if err != nil || got != "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" {
		t.Fatalf("解析失败：got=%q err=%v", got, err)
	}

	// 大写应被归一成小写（不同工具的 sha256 输出大小写不一致）
	up := "E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855  x\n"
	if got, err := parseSha256(up); err != nil || got != strings.ToLower(got) {
		t.Fatalf("大写哈希未归一：got=%q err=%v", got, err)
	}

	// 前后有空行 / 无关行时应跳过
	mixed := "\n# generated by CI\n" + good + "\n"
	if got, err := parseSha256(mixed); err != nil || len(got) != 64 {
		t.Fatalf("含噪声行时解析失败：got=%q err=%v", got, err)
	}

	// 非法输入必须报错，不能返回空串让调用方拿空哈希去比对
	bad := []string{
		"",
		"\n\n",
		"not a hash",
		"abc123",
		"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b85", // 63 位
		"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
	}
	for _, b := range bad {
		if got, err := parseSha256(b); err == nil {
			t.Errorf("非法输入 %q 应报错，实际返回 %q", b, got)
		}
	}
}

// installBinary 是自更新里唯一改文件系统的一段。重点验证：
//   - 成功后 target 是新内容、权限可执行、旧内容留在 .bak
//   - target 不存在时也能装（备份置空）
//   - 失败路径不破坏 target
func TestInstallBinary(t *testing.T) {
	dir := t.TempDir()
	target := filepath.Join(dir, "dsh-admin")
	if err := os.WriteFile(target, []byte("OLD"), 0o755); err != nil {
		t.Fatal(err)
	}

	backup, err := installBinary(target, []byte("NEW-CONTENT"))
	if err != nil {
		t.Fatalf("installBinary 失败：%v", err)
	}
	got, _ := os.ReadFile(target)
	if string(got) != "NEW-CONTENT" {
		t.Errorf("target 内容 = %q，期望 NEW-CONTENT", got)
	}
	if backup == "" {
		t.Error("应返回备份路径")
	} else if b, _ := os.ReadFile(backup); string(b) != "OLD" {
		t.Errorf("备份内容 = %q，期望 OLD", b)
	}
	// 必须可执行，否则重启后起不来
	if st, err := os.Stat(target); err != nil {
		t.Fatal(err)
	} else if st.Mode().Perm()&0o111 == 0 {
		t.Errorf("target 权限 = %v，缺少可执行位", st.Mode().Perm())
	}
	// 临时文件不应残留
	left, _ := filepath.Glob(filepath.Join(dir, ".dsh-admin.new.*"))
	if len(left) != 0 {
		t.Errorf("残留临时文件：%v", left)
	}
}

// target 不存在时也要能装（首次安装 / .bak 场景）
func TestInstallBinaryNoExistingTarget(t *testing.T) {
	dir := t.TempDir()
	target := filepath.Join(dir, "dsh-admin")

	backup, err := installBinary(target, []byte("FRESH"))
	if err != nil {
		t.Fatalf("target 不存在时应能安装：%v", err)
	}
	if backup != "" {
		t.Errorf("target 不存在时不应有备份，实际 %q", backup)
	}
	if got, _ := os.ReadFile(target); string(got) != "FRESH" {
		t.Errorf("内容 = %q，期望 FRESH", got)
	}
}

// 目录不可写时必须报错，且不能留下半截文件
func TestInstallBinaryUnwritableDir(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("root 会无视权限位，跳过")
	}
	dir := t.TempDir()
	target := filepath.Join(dir, "dsh-admin")
	if err := os.WriteFile(target, []byte("OLD"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(dir, 0o500); err != nil {
		t.Fatal(err)
	}
	defer os.Chmod(dir, 0o700) // 让 TempDir 清理能进行

	if _, err := installBinary(target, []byte("NEW")); err == nil {
		t.Error("目录不可写时应报错")
	}
	os.Chmod(dir, 0o700)
	if got, _ := os.ReadFile(target); string(got) != "OLD" {
		t.Errorf("失败后 target 被破坏：%q", got)
	}
}

// 只支持有发布产物的架构；其他架构必须明确报错，而不是去下一个不存在的文件
func TestPanelArch(t *testing.T) {
	arch, err := panelArch()
	switch runtime.GOARCH {
	case "amd64", "arm64":
		if err != nil || arch != runtime.GOARCH {
			t.Errorf("GOARCH=%s 应返回对应产物名，实际 arch=%q err=%v", runtime.GOARCH, arch, err)
		}
	default:
		if err == nil {
			t.Errorf("GOARCH=%s 应报错，实际返回 %q", runtime.GOARCH, arch)
		}
	}
}

// 备份必须是**复制**出来的，不能在替换过程中让 target 消失。
//
// 早先的实现是 `os.Rename(target, backup)` 再 `os.Rename(tmp, target)` —— 两步之间
// target **不存在**，此刻被 kill / 断电就会留下"没有可执行文件、只剩 .bak"的状态，
// systemd 的 Restart=on-failure 也拉不起来。
// 这里把第一次 rename 前的那一刻暴露出来做断言：备份已经存在（复制完成），
// 而 target 仍然在位且内容还是旧的。
func TestInstallBinaryNeverRemovesTarget(t *testing.T) {
	dir := t.TempDir()
	target := filepath.Join(dir, "dsh-admin")
	if err := os.WriteFile(target, []byte("OLD"), 0o755); err != nil {
		t.Fatal(err)
	}

	// 用 hook 在"备份完成、准备 rename 到位"之间插一次检查。
	var sawBackupWithoutTarget bool
	var backupContentWhileTargetGone string
	hook = func() {
		if _, err := os.Stat(target); err != nil {
			sawBackupWithoutTarget = true
			if b, err := os.ReadFile(target + ".bak"); err == nil {
				backupContentWhileTargetGone = string(b)
			}
		}
	}
	defer func() { hook = nil }()

	backup, err := installBinary(target, []byte("NEW"))
	if err != nil {
		t.Fatalf("installBinary 失败：%v", err)
	}
	if sawBackupWithoutTarget {
		t.Errorf("替换过程中 target 一度不存在（此刻断电就没有可执行文件了），备份内容 = %q",
			backupContentWhileTargetGone)
	}
	if backup == "" {
		t.Fatal("应返回备份路径")
	}
	if b, _ := os.ReadFile(backup); string(b) != "OLD" {
		t.Errorf("备份内容 = %q，期望 OLD", b)
	}
	if got, _ := os.ReadFile(target); string(got) != "NEW" {
		t.Errorf("target 内容 = %q，期望 NEW", got)
	}
}

// 连续的两次自更新：第二次的备份必须是**第一次装上的那个版本**（旧内容），
// 而不是被第一次覆盖掉。`os.Rename(target, backup)` 时 backup 会被原子替换，
// 语义相同；改成复制后同样要保证这一点。
func TestInstallBinaryBackupIsPreviousVersion(t *testing.T) {
	dir := t.TempDir()
	target := filepath.Join(dir, "dsh-admin")
	if err := os.WriteFile(target, []byte("V1"), 0o755); err != nil {
		t.Fatal(err)
	}
	if _, err := installBinary(target, []byte("V2")); err != nil {
		t.Fatal(err)
	}
	backup, err := installBinary(target, []byte("V3"))
	if err != nil {
		t.Fatal(err)
	}
	if b, _ := os.ReadFile(backup); string(b) != "V2" {
		t.Errorf("第二次自更新的备份 = %q，期望 V2（第一次装上那版，可用于回滚）", b)
	}
	if got, _ := os.ReadFile(target); string(got) != "V3" {
		t.Errorf("target = %q，期望 V3", got)
	}
}

// compareVersions：本项目只用到「日期 + 可选序号」这种形态，但比较必须是数值感知的
// —— 字符串比较会把 "2026.10.9" 判成比 "2026.10.30" 新（9 > 3），于是"拒降级"会误判。
func TestCompareVersions(t *testing.T) {
	cases := []struct {
		a, b string
		want int
	}{
		{"v2026.10.01-3", "v2026.10.01-3", 0},
		{"2026.10.01-3", "v2026.10.01-3", 0}, // 前缀 v 不影响
		{"v2026.10.01-3", "v2026.10.01-2", 1},
		{"v2026.10.01-2", "v2026.10.01-3", -1},
		// 数值感知：字符串比 "9" > "30"，那是错的
		{"v2026.10.9", "v2026.10.30", -1},
		{"v2026.10.30", "v2026.10.9", 1},
		{"v2026.9.1", "v2026.10.1", -1},
		// dev 视为最旧：开发构建不该被认为比发布版新
		{"dev", "v2026.10.01-1", -1},
		{"v2026.10.01-1", "dev", 1},
		{"dev", "", 0},
	}
	for _, c := range cases {
		if got := compareVersions(c.a, c.b); got != c.want {
			t.Errorf("compareVersions(%q, %q) = %d，期望 %d", c.a, c.b, got, c.want)
		}
	}
}

// verifyDownloadedBinary：跑得起来 + 不降级。
// 用一个能自报版本号的假二进制（shell 脚本模拟 -version 的输出）。
func TestVerifyDownloadedBinary(t *testing.T) {
	mk := func(version string) []byte {
		return []byte("#!/bin/sh\necho '" + version + "'\n")
	}

	// ① 能跑且版本更新 → 通过，并回报它自己的版本
	got, err := verifyDownloadedBinary(mk("v2026.10.01-4"), "v2026.10.01-3")
	if err != nil {
		t.Fatalf("更新的版本应通过，却报错：%v", err)
	}
	if got != "v2026.10.01-4" {
		t.Errorf("回报的版本 = %q，期望 v2026.10.01-4（应是**新装上的**那个）", got)
	}

	// ② 同版本 → 允许（幂等重装）
	if _, err := verifyDownloadedBinary(mk("v2026.10.01-3"), "v2026.10.01-3"); err != nil {
		t.Errorf("同版本应允许，却报错：%v", err)
	}

	// ③ 更旧的版本 → 必须拒绝。latest 别名指向旧 release 时全靠这道闸门。
	_, err = verifyDownloadedBinary(mk("v2026.09.01-1"), "v2026.10.01-3")
	if err == nil {
		t.Error("更旧的版本应被拒绝（降级闸门失效）")
	} else if !strings.Contains(err.Error(), "拒绝降级") {
		t.Errorf("错误信息应说明是拒降级，实际：%v", err)
	}

	// ④ 跑不起来的产物（架构不对 / 动态链接缺失 / 坏文件）→ 必须拒绝，
	//    而不是"成功地"装上一个起不来的二进制。
	_, err = verifyDownloadedBinary([]byte("not an executable at all"), "v2026.10.01-3")
	if err == nil {
		t.Error("跑不起来的产物应被拒绝")
	} else if !strings.Contains(err.Error(), "无法执行") {
		t.Errorf("错误信息应说明跑不起来，实际：%v", err)
	}

	// ⑤ 能跑但什么都不输出 → 拒绝（拿不到版本号就无法判断是否降级）
	_, err = verifyDownloadedBinary([]byte("#!/bin/sh\nexit 0\n"), "v2026.10.01-3")
	if err == nil {
		t.Error("不报告版本号的产物应被拒绝")
	}
}
